FROM node:18-alpine

WORKDIR /app

RUN npm install --location=global npm@8.12.1

COPY package.json .

RUN npm config set unsafe-perm true

RUN npm install --force

COPY . .

CMD ["npm", "run", "start"]
